apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{USER_NAMESPACE}}
  name: user-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-role-binding
  namespace: {{USER_NAMESPACE}}
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: user-role
  apiGroup: rbac.authorization.k8s.io
